export ZSH=~/.dotfiles/zsh/oh-my-zsh

ZSH_THEME="zoli"

# Example aliases
source ~/.dotfiles/zsh/aliases

plugins=(common-aliases ubuntu colored-man cp github git-flow git-prompt go python pip npm systemd systemadmin)

source $ZSH/oh-my-zsh.sh

source ~/.dotfiles/zsh/env

export EDITOR='vim'

if [ -e /usr/share/terminfo/x/xterm-256color ]; then
	export TERM='xterm-256color'
else
	export TERM='xterm-color'
fi

