FROM zidom/arch
MAINTAINER Mohammad Zolfaghari <zidom72@gmail.com>

RUN yay -S --noconfirm python nodejs npm pango imagemagick mongodb-bin mongodb-tools-bin perl-image-exiftool

RUN sudo ln -s /usr/sbin/vendor_perl/exiftool /usr/bin/exiftool
